; Perform simple addition

LDA #01
STA $01
LDA #02
STA $02
ADC $01
STA $03

		.byte	$0d, $0a, $00
		.ascii	"WWWWWWWWWWWWWWWWBBBBBBBBBBBBBBBBWWWWWWWWWWWWWWWW"
		.byte	"KQCCBBRRPPPPPPPPKQCCBBRRPPPPPPPP"
		.byte	$00
